## RF Remote 1

## Turn on RF Remote1 Button A
- platform: mqtt
  name: "RF_Remote1_A"
  payload_on: !secret rf_remote_1a
  payload_off: "Remote1ButtonAoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote1 Button B
- platform: mqtt
  name: "RF_Remote1_B"
  payload_on: !secret rf_remote_1b
  payload_off: "Remote1ButtonBoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote1 Button C
- platform: mqtt
  name: "RF_Remote1_C"
  payload_on: !secret rf_remote_1c
  payload_off: "Remote1ButtonCoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote1 Button D
- platform: mqtt
  name: "RF_Remote1_D"
  payload_on: !secret rf_remote_1d
  payload_off: "Remote1ButtonDoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'

## RF Remote 2

## Turn on RF Remote2 Button A
- platform: mqtt
  name: "RF_Remote2_A"
  payload_on: !secret rf_remote_2a
  payload_off: "Remote2ButtonAoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote2 Button B
- platform: mqtt
  name: "RF_Remote2_B"
  payload_on: !secret rf_remote_2b
  payload_off: "Remote2ButtonBoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote2 Button C
- platform: mqtt
  name: "RF_Remote2_C"
  payload_on: !secret rf_remote_2c
  payload_off: "Remote2ButtonCoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
## Turn on RF Remote2 Button D
- platform: mqtt
  name: "RF_Remote2_D"
  payload_on: !secret rf_remote_2d
  payload_off: "Remote2ButtonDoff"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
