homeassistant:
  ## Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  ## Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  ## C for Celcius, F for Fahrenheit
  temperature_unit: C
  ## metric for Metric, imperial for Imperial
  unit_system: metric
  ## Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  ## Device Customised names, icons, etc
  customize: !include_dir_merge_named customize
  ## Packages?
  # packages: !include_dir_named packages

## Show links to resources in log and frontend
#introduction:

## Enables the frontend
frontend:

## Allows you to issue voice commands from the frontend in enabled browsers
conversation:

## View all events in a logbook
logbook:

## Enables support for tracking state changes over time.
history:

## Enable configure panel
config:

## Show map on UI
map:

## Discover some devices automatically
discovery:

## Track the sun
sun:

## Checks for available updates
## https://www.home-assistant.io/components/updater
updater:

## System Health Component
## https://www.home-assistant.io/components/system_health
system_health:

## HTTP Core Component
## https://www.home-assistant.io/components/http/
http:
  ## Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

## Enables support for tracking
## https://www.home-assistant.io/components/recorder
recorder:
  purge_interval: 1  ## (days) Enable scheduled purge of older events and states
  purge_keep_days: 7  ## (days) Specify number of history days to keep in recorder database after purge
  db_url: !secret dburl_mariadb_addon  ## The URL which point to your database
  ## Specify domains of metrics to keep
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - light
  #     - device_tracker
  #     - climate
  #   entities:
  #     - sun.sun
  #     - input_number.temp_target
  # exclude:
  #   entities:
  #     - sensor.date
  #     - sensor.time

## Setup tracking using InfluxDB
## https://www.home-assistant.io/components/influxdb
# influxdb:
#   host: !secret dburl_influxdb
#   port: !secret dburl_influxdb_port
#   database: !secret dburl_influxdb_name
#   username: !secret dburl_influxdb_username
#   password: !secret dburl_influxdb_password
#   ssl: true
#   verify_ssl: true
#   max_retries: 3
#   default_measurement: state
#   tags:
#    instance: prod
#    source: hass

## Open Z-Wave configuration!
## https://www.home-assistant.io/components/zwave
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_networkkey
#   config_path: /srv/hass/src/python-openzwave/openzwave/config

## Integrated MQTT Server
## https://www.home-assistant.io/components/mqtt
mqtt:
#  broker: 127.0.0.1
  broker: 192.168.178.130
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
#  certificate: /home/paulus/dev/addtrustexternalcaroot.crt
#  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

## Ring.com doorbell
## https://www.home-assistant.io/components/ring
ring:
  username: !secret ring_username
  password: !secret ring_password

## Vera gateway for Z-Wave & Zigbee
## https://www.home-assistant.io/components/vera
vera:
  vera_controller_url: http://192.168.178.22:3480/

## Xiaomi component for Zigbee temp sensors and buttons
## https://www.home-assistant.io/components/xiaomi_aqara
xiaomi_aqara:
  discovery_retry: 10
  gateways:
   - mac: !secret xiaomi_mac_address
     key: !secret xiaomi_password
     host: '192.168.178.23'
     disable: false

## Enable fans/air filters
fan:
  ## Xiaomi Air Purifier 2S setup
  ## https://www.home-assistant.io/components/fan.xiaomi_miio/
  - platform: xiaomi_miio
    host: 192.168.178.175
    token: !secret xiaomi_access_token_europe

## notify service for sending notifications
notify:
  ## Pushbullet Setup
  ## https://www.home-assistant.io/components/notify.pushbullet/
  - name: pushbullet
    platform: pushbullet
    api_key: !secret apikey_pushbullet

## Enable Google Assistant API
## https://www.home-assistant.io/components/google_assistant
google_assistant: !include_dir_merge_named google_assistant

## Enable Text-To-Speech
tts:
  ## TTS for Google Assistant
  ## https://www.home-assistant.io/components/tts.google
  - platform: google

## Sabnzbd download manager
## https://www.home-assistant.io/components/sabnzbd
sabnzbd:
  api_key: !secret apikey_sabnzbd
  host: 192.168.178.103
  name: sab
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

## Setup Thermostats and climate controllers
climate:
  ## Custom Thermostat
  ## https://www.home-assistant.io/components/climate.generic_thermostat
  - platform: generic_thermostat
    name: House Heating
    heater: switch.pi_boiler_switch
    target_sensor: !secret xiaomi_temp_2
    min_temp: 10
    max_temp: 25
    target_temp: 21 # don't forget to also set input_number.temp_target
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 1

## Digital return value (0 or 1) sensors
binary_sensor:
  ## Ring binary sensor
  ## https://www.home-assistant.io/components/ring/#binary-sensor
  - platform: ring
    monitored_conditions:
      - ding
      - motion

## Front Page Input States and Options, used for Automation
input_select:
  presence_house:
    name: Who's Home?
    options:
      - Home
      - Away
      - Home Guests
      - Away Guests
      # - Night
      # - Vacation
    initial: Away
    icon: mdi:home-map-marker

# ## Iframes for local services
# panel_iframe:
#   router:
#     title: zRouter
#     icon: mdi:wrench
#     url: https://192.168.178.1
#   configurator:
#     title: zConfigurator
#     icon: mdi:wrench
#     url: http://192.168.178.130:3218

## Media Player (Plex, Spotify, etc)
media_player: !include_dir_merge_list media_player

## Setup lights (Yeelight, MiLight, etc)
light: !include_dir_merge_list light

## Automation programs
automation: !include automations.yaml
automation old: !include_dir_merge_list automation

## Device Tracker module
device_tracker: !include_dir_merge_list device_tracker

## Views (Tabs) and Groups
group: !include_dir_merge_named group

## Sets of on/off boolean switches
input_boolean: !include_dir_merge_named input_boolean

## Virtual input number sliders
input_number: !include_dir_merge_named input_number

## Scene setups
# scene: !include_dir_merge_list scene

## Scripts for automation
script: !include_dir_merge_named script

## Custom sensors
sensor: !include_dir_merge_list sensor

## Shell commands for automations
shell_command: !include_dir_merge_named shell_command

## Switches physical (eg: GPIO) and virtual
switch: !include_dir_merge_list switch

## Zones using GPS
zone: !include_dir_merge_list zone