homeassistant:
  ## Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  ## Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  ## C for Celcius, F for Fahrenheit
  temperature_unit: C
  ## metric for Metric, imperial for Imperial
  unit_system: metric
  ## Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  ## Device Customised names, icons, etc
  customize: !include_dir_merge_named customize
  ## Packages?
  # packages: !include_dir_named packages

## Show links to resources in log and frontend
#introduction:

## Enables the frontend
frontend:

## Allows you to issue voice commands from the frontend in enabled browsers
conversation:

## View all events in a logbook
logbook:

## Enables support for tracking state changes over time.
history:

## Enable configure panel
config:

## Show map on UI
map:

## Discover some devices automatically
discovery:

## Track the sun
sun:

## Checks for available updates
updater:

http:
  ## Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

## Enables support for tracking
recorder:
  ## (days) Enable scheduled purge of older events and states
  purge_interval: 5
  ## (days) Specify number of history days to keep in recorder database after purge
  ## You can use service call recorder.purge when needed
  purge_keep_days: 10
  ## The URL which point to your database
  # db_url: !secret dburl_mariadb
  ## Specify domains of metrics to keep
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - light
  #     - device_tracker
  #     - climate
  #   entities:
  #     - sun.sun
  #     - input_number.target_temp
  # exclude:
  #   entities:
  #     - sensor.date
  #     - sensor.time

## Setup tracking using InfluxDB
# influxdb:
#   host: !secret dburl_influxdb
#   port: !secret dburl_influxdb_port
#   database: !secret dburl_influxdb_name

  # username: !secret dburl_influxdb_username
  # password: !secret dburl_influxdb_password
  # ssl: true
  # verify_ssl: true
  # max_retries: 3
  # default_measurement: state
  # tags:
  #  instance: prod
  #  source: hass

## Open Z-Wave configuration!
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_networkkey
  # config_path: /srv/hass/src/python-openzwave/openzwave/config

## Vera gateway for Z-Wave & Zigbee
vera:
  vera_controller_url: !secret vera_url

## Xiaomi component for temp sensors and buttons
xiaomi_aqara:
  gateways:
   - mac: !secret mac_address_xiaomi
     key: !secret xiaomi_password

## Enable Google Assistant API
google_assistant:
  project_id: !secret google_assistant_project_id
  # client_id: !secret google_assistant_client_id
  # access_token: !secret google_assistant_access_token
  # agent_user_id: google_assistant_agent_user_id
  api_key: google_assistant_api_key
  exposed_domains:
     - group
    #  - input_boolean
     - scene
     - script
     - switch
    #  - fan
     - light
    #  - cover
     - media_player
     - climate
  entity_config:
    group.bedroom_things:
      name: Bedroom Things
      aliases:
        - Bedroom Stuff
    group.livingroom_things:
      name: Livingroom Things
      aliases:
        - Livingroom Stuff
        - Living room Stuff
    # switch.pi_door_strike:
    #   name: Door Strike
    #   aliases:
    #     - Buzz the door
    # group.optimus:
    #   name: optimus
    #   aliases:
    #     - workstation
    #     - the key to vector sigma
    # group.soundwave:
    #   name: soundwave
    #   aliases:
    #     - server
    #     - the tape deck

## Ring.com doorbell
ring:
  username: !secret ring_username
  password: !secret ring_password

## Sabnzbd download manager
sabnzbd:
  api_key: !secret apikey_sabnzbd
  host: 192.168.178.103
  name: sab
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

## Pushbullet Token/API setup (Disabled in January)
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret apikey_pushbullet

mqtt:
#  broker: 127.0.0.1
  broker: 192.168.178.130
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
#  certificate: /home/paulus/dev/addtrustexternalcaroot.crt
#  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

media_player:
  - platform: cast
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: true
    use_custom_entity_ids: false
    use_episode_art: false

climate:
  - platform: generic_thermostat
    name: House Heating
    heater: switch.pi_boiler_switch
    target_sensor: !secret xiaomi_temp_2
    min_temp: 10
    max_temp: 25
    target_temp: 21
    cold_tolerance: 0.3
    hot_tolerance: 0
    icon: mdi:guage
    min_cycle_duration:
      minutes: 1

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

light:
  - platform: yeelight
    devices:
      192.168.178.151:
        name: Yeelight 1
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.152:
        name: Yeelight 2
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.153:
        name: Yeelight 3
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.154:
        name: Yeelight 4
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)

# Front Page Input States and Options, used for Automation
input_select:
  house_presence:
    name: Who's Home?
    options:
      - Home
      - Nobody Home
      - Lady and The Tramp
      - lady ALONE
      - Night
      # - Warm House
      # - Visitors
      # - Visitors with Kids
      # - Open Door!
      # - Intruder!
      # - Emergency!
    initial: Nobody Home
    icon: mdi:home-map-marker

## Automation programs
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
## Device Tracker module
device_tracker: !include_dir_merge_list device_tracker
## Views (Tabs) and Groups
group: !include_dir_merge_named group
## Sets of on/off boolean switches
input_boolean: !include_dir_merge_named input_boolean
## Virtual input number sliders
input_number: !include_dir_merge_named input_number
## Scene setups
# scene: !include_dir_merge_list scene
## Scripts for automation
script: !include_dir_merge_named script
## Custom sensors
sensor: !include_dir_merge_list sensor
## Shell commands for automations
shell_command: !include_dir_merge_named shell_command
## Switches physical (eg: GPIO) and virtual
switch: !include_dir_merge_list switch
## Zones using GPS
zone: !include_dir_merge_list zone