################################
## HOME ASSISTANT CORE
## Core config for Home Assistant

homeassistant:
  ## Name of the location where Home Assistant is running
  # name: Home
  ## Location required to calculate the time the sun rises and sets
  # latitude: !secret home_latitude
  # longitude: !secret home_longitude
  ## Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: !secret home_elevation
  ## metric for Metric, imperial for Imperial
  # unit_system: metric
  ## Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: !secret home_timezone
  ## Device Customised names, icons, etc
  customize: !include customize.yaml
  ## This adds custom externalised packages, like NotoriousBDG's 'Battery Alert'.
  ## Battery Alert from: https://github.com/notoriousbdg/Home-AssistantConfig/blob/master/packages/battery_alert.yaml
  packages: !include_dir_named packages

################################
## CORE PACKAGES
## Packages configured standard in Home Assistant

## Enable configure panel
config:

## Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

## Discover some devices automatically
discovery:

## Downloader to download files
## https://www.home-assistant.io/components/downloader
downloader:
  download_dir: downloads

## Enables the frontend
frontend:

## Enables support for tracking state changes over time.
history:

## Display a graph similar to the graphs in more-info popups and the history panel.
## https://www.home-assistant.io/components/history_graph
# history_graph:
#   air_quality:
#     name: Air Quality
#     entities:
#       - sensor.attribute_fan_aqi
#       - sensor.attribute_fan_favorite_level
#       - sensor.attribute_fan_temperature
#     hours_to_show: 168 # 168 = 7 days / 1 week, 240 = 10 days
#     refresh: 60
#   battery_levels:
#     name: Air Quality
#     entities:
#       - sensor.attribute_fan_aqi
#       - sensor.attribute_fan_favorite_level
#       - sensor.attribute_fan_temperature
#     hours_to_show: 240 # 168 = 7 days / 1 week, 240 = 10 days
#     refresh: 60

## HTTP Core Component
## https://www.home-assistant.io/components/http/
http:
  # base_url: !secret http_base_url
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # ssl_certificate: /ssl/letsencrypt/live/straker-me/fullchain.pem
  # ssl_key: /ssl/letsencrypt/live/straker-me/privkey.pem

## Authentication Providers
## https://www.home-assistant.io/docs/authentication/providers/
# auth_providers:
#   - type: legacy_api_password
#     ## Uncomment this to add a password (recommended!)
#     api_password: !secret http_api_password

## View all events in a logbook
logbook:

## Setup logging for debugging
logger:
  default: warning
  logs:
    limitlessled: debug

## Show map on UI
map:

## Iframes for local services
## https://www.home-assistant.io/components/panel_iframe/
# panel_iframe:
#   configurator:
#     title: 'zConfigurator'
#     url: 'http://192.168.178.130:3218'
#     icon: mdi:wrench
#   fang1:
#     title: 'zZfang1'
#     url: 'https://192.168.178.171'
#     icon: mdi:camera-wireless
#   fang2:
#     title: 'zZfang2'
#     url: 'https://192.168.178.172'
#     icon: mdi:camera-wireless
#   fang3:
#     title: 'zZfang3'
#     url: 'https://192.168.178.173'
#     icon: mdi:camera-wireless
#   fang4:
#     title: 'zZfang4'
#     url: 'https://192.168.178.174'
#     icon: mdi:camera-wireless
#   router:
#     title: 'zRouter'
#     url: 'https://192.168.178.1'
#     icon: mdi:wrench
#   sonoff1:
#     title: 'zSonoff1'
#     url: 'http://192.168.178.31'
#     icon: mdi:electric-switch
#   sonoff2:
#     title: 'zSonoff2'
#     url: 'http://192.168.178.32'
#     icon: mdi:electric-switch
#   sonoff3:
#     title: 'zSonoff3'
#     url: 'http://192.168.178.33'
#     icon: mdi:electric-switch
#   sonoff4:
#     title: 'zSonoff4'
#     url: 'http://192.168.178.34'
#     icon: mdi:electric-switch
#   tasmoadmin:
#     title: 'zSonWEB'
#     url: 'http://192.168.178.130:9541'
#     icon: mdi:lightbulb-on

## Enables support for tracking
## https://www.home-assistant.io/components/recorder
recorder:
  db_url: !secret dburl_mariadb_addon  ## The URL which point to your database

## Track the sun
sun:

## System Health Component
## https://www.home-assistant.io/components/system_health
system_health:

## Checks for available updates
## https://www.home-assistant.io/components/updater
updater:

################################
## EXTERNALLY CONFIGURED PACKAGES
## Not core to Home Assistant but configured here

## notify service for sending notifications
notify:
  ## Pushbullet Setup
  ## https://www.home-assistant.io/components/notify.pushbullet/
  - name: pushbullet
    platform: pushbullet
    api_key: !secret apikey_pushbullet

## Integrated MQTT Server
## https://www.home-assistant.io/components/mqtt
mqtt:
#  broker: 127.0.0.1
  broker: 192.168.178.130
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
#  certificate: /home/paulus/dev/addtrustexternalcaroot.crt
#  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

## Owntracks via MQTT for mobile tracking
## https://www.home-assistant.io/components/owntracks/
owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: false
#   track_new_devices: yes
#   interval_seconds: 240
#   consider_home: 600 ## was 900
#   waypoint_whitelist:
#     - kareem
#     - magnus4
#   region_mapping:
#     cabin: home
#     office: work

## Open Z-Wave configuration!
## https://www.home-assistant.io/components/zwave
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_networkkey
#   config_path: /srv/hass/src/python-openzwave/openzwave/config

## Vera gateway for Z-Wave & Zigbee
## https://www.home-assistant.io/components/vera
vera:
  vera_controller_url: http://192.168.178.22:3480/

## IKEA Tradfri for Zigbee
## https://www.home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.178.27

## Xiaomi component for Zigbee temp sensors and buttons
## https://www.home-assistant.io/components/xiaomi_aqara
# xiaomi_aqara:
#   discovery_retry: 10
#   gateways:
#   - mac: !secret xiaomi_mac_address
#     key: !secret xiaomi_password
#     host: '192.168.178.23'
#     disable: false

## Enable fans/air filters
fan:
  ## Xiaomi Air Purifier 2S setup
  ## https://www.home-assistant.io/components/fan.xiaomi_miio/
  - platform: xiaomi_miio
    name: "air_purifier_2s"
    host: 192.168.178.175
    token: !secret xiaomi_access_token_europe

## Enable Xiaomi Mi Remote(s)
remote:
  ## https://www.home-assistant.io/integrations/remote.xiaomi_miio
  ## https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/#retrieving-the-access-token
  ## https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md
  ## https://android-apk.org/com.xiaomi.smarthome/43397902-mi-home/
  - platform: xiaomi_miio
    name: "livingroom_ir_remote"
    host: 192.168.178.176
    token: !secret xiaomi_access_token_mi_remote_1
    commands:
      tv_on_off:
        command:
          - raw:mUznMwlk2mEwlkxmM3AIWazYAcpiAgYDLTUAcprOAEDAEIBkwIXAp+WTWagQeAPMwgA=
      tv_source:
        command:
          - raw:mUznMwlk1nEwlkxmIBBTaYAGEAg8ymIBCzWagMEAWYDHgITMgENAH8Ac5hAA
      tv_mute:
        command:
          - raw:mUznMwlk1nAAZAD9MZlMgCCm4CHgU+AwcxAEKbTEBjwA6APKYQA=
      tv_volume_up:
        command:
          - raw:mUznMwlk1nAAZADtMZiAQU2mACEgMRMpiAg02AgIAswGPAx8CiABymEA
      tv_volume_down:
        command:
          - raw:mUznMwlk1nEwlkxmUxAIaYgIlNpgAYoAdgQwAHE2AoIBMpjMQDCAIOaglsAPAFFTCAA=
      tv_prog_up:
        command:
          - raw:mU0mEwlk1m4AZTkAMpwAP4A7APlMZlMgENAgcBhQQfAH6YQA
      tv_prog_down:
        command:
          - raw:mUznMwlk1nEwlkxmUxAIWagIMAP8xmIAhTYCQwGPmUyAx8Af5hLJhAA=

## Enable Text-To-Speech, used by Google Assistant
tts:
  ## TTS for Google Assistant
  ## https://www.home-assistant.io/components/google_translate/
  - platform: google_translate
    language: 'en'
    cache: true
    cache_dir: /config/tts
    time_memory: 300
    # base_url: http://192.168.178.10:8123
    service_name: google_say # default google_translate_say

## Setup tracking using InfluxDB
## https://www.home-assistant.io/components/influxdb
# influxdb:
#   host: !secret dburl_influxdb
#   port: !secret dburl_influxdb_port
#   database: !secret dburl_influxdb_name
#   username: !secret dburl_influxdb_username
#   password: !secret dburl_influxdb_password
#   ssl: true
#   verify_ssl: true
#   max_retries: 3
#   default_measurement: state
#   tags:
#    instance: prod
#    source: hass

## Sabnzbd download manager
## https://www.home-assistant.io/components/sabnzbd
# sabnzbd:
#   api_key: !secret apikey_sabnzbd
#   host: 192.168.178.11
#   name: SABnzbd
#   port: 8080
#   ssl: false
#   sensors:
#     - current_status
#     - speed
#     - queue_size
#     - queue_remaining
#     - disk_size
#     - disk_free
#     - queue_count
#     - day_size
#     - week_size
#     - month_size
#     - total_size

## Spotify Media Player
## https://www.home-assistant.io/integrations/spotify/
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

## Spotify custom_component for playing to Chromecast/Google Home
## https://github.com/fondberg/spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

################################
## EXTERNALISED PACKAGES
## Packages that are in sub_dirs of the main configuration
## Mixed core components and external components

## Automation programs
automation: !include automations.yaml
automation old: !include_dir_merge_list automation

## Digital return value (0 or 1) sensors
binary_sensor: !include_dir_merge_list binary_sensor

## Cameras
camera: !include_dir_merge_list camera

## Setup Thermostats and climate controllers
climate:
  ## Custom Thermostat
  ## https://www.home-assistant.io/components/climate.generic_thermostat
  - platform: generic_thermostat
    name: House Heating
    heater: switch.relay4c1_1 # operate this switch for heating on/of
    target_sensor: !secret xiaomi_temp_2 # sensor to monitor to determine switch
    min_temp: 10
    max_temp: 25
    target_temp: 20 # don't forget to also set input_number.temp_target
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 1

## Device Tracker module - Manage tracked devices
## https://www.home-assistant.io/components/device_tracker/
device_tracker: !include_dir_merge_list device_tracker

## Enable Google Assistant API
## https://www.home-assistant.io/components/google_assistant
google_assistant: !include_dir_merge_named google_assistant

## Views (Tabs) and Groups
group: !include_dir_merge_named group

## Sets of on/off boolean switches
input_boolean: !include_dir_merge_named input_boolean

## Virtual input number sliders
input_number: !include_dir_merge_named input_number

## Front Page Input States and Options, used for Automation
input_select: !include_dir_merge_named input_select

## Setup lights (MiLight, etc)
light: !include_dir_merge_list light

## Media Player (Plex, Spotify, etc)
media_player: !include_dir_merge_list media_player

## Scene setups
# scene: !include_dir_merge_list scene

## Scripts for automation
script: !include_dir_merge_named script

## Custom sensors
sensor: !include_dir_merge_list sensor

## Shell commands for automations
shell_command: !include_dir_merge_named shell_command

## Switches physical (eg: GPIO) and virtual
switch: !include_dir_merge_list switch

## Timers for automations: heating, lights, etc
## https://www.home-assistant.io/components/timer
timer:
  temperature_boost:
    duration: '02:00:00'
  light_entrance:
    duration: '00:03:00'
  light_downstairs:
    duration: '00:03:00'
  light_livingroom_spots:
    duration: '00:03:00'
  light_livingroom_table:
    duration: '00:03:00'
  light_upstairs_night:
    duration: '00:03:00'
  light_upstairs:
    duration: '00:03:00'
  light_closet_night:
    duration: '00:03:00'
  light_closet:
    duration: '00:03:00'
  light_toilet:
    duration: '00:03:00'
  light_pantry:
    duration: '00:03:00'
  light_kitchen:
    duration: '00:03:00'
  light_bathroom:
    duration: '00:03:00'

## Zones using GPS
zone: !include_dir_merge_list zone

websocket_api:
