homeassistant:
  ## Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  ## Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  ## C for Celcius, F for Fahrenheit
  temperature_unit: C
  ## metric for Metric, imperial for Imperial
  unit_system: metric
  ## Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone

  customize: !include customization.yaml

## Show links to resources in log and frontend
#introduction:

## Enables the frontend
frontend:

## Allows you to issue voice commands from the frontend in enabled browsers
conversation:

## View all events in a logbook
logbook:

## Enables support for tracking state changes over time.
history:

## Enable configure panel
config:

## Show map on UI
map:

## Discover some devices automatically
discovery:

## Track the sun
sun:

## Checks for available updates
updater:

## Automation programs
automation: !include automations.yaml

## Scripts
script: !include scripts.yaml

## Views (Tabs) and Groups
group: !include groups.yaml

## Zones using GPS
zone: !include zones.yaml

## Example configuration.yaml entry
device_tracker: !include device_tracker.yaml

http:
  ## Uncomment this to add a password (recommended!)
  api_password: !secret api_password
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  ssl_certificate: /ssl/letsencrypt/live/straker-me/fullchain.pem
#  ssl_key: /ssl/letsencrypt/live/straker-me/privkey.pem
#  /data/letsencrypt/live/straker.me/fullchain.pem

## Enables support for tracking
recorder:
  ## (days) Enable scheduled purge of older events and states
  purge_interval: 5
  ## (days) Specify number of history days to keep in recorder database after purge
  ## You can use service call recorder.purge when needed
  purge_keep_days: 10
  ## The URL which point to your database
  # db_url: !secret dburl_mariadb
  ## Specify domains of metrics to keep
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - light
  #     - device_tracker
  #     - climate
  #   entities:
  #     - sun.sun
  #     - input_number.target_temp
  # exclude:
  #   entities:
  #     - sensor.date
  #     - sensor.time

## Setup tracking using InfluxDB
# influxdb:
#   host: !secret dburl_influxdb
#   port: !secret dburl_influxdb_port
#   database: !secret dburl_influxdb_name

  # username: !secret dburl_influxdb_username
  # password: !secret dburl_influxdb_password
  # ssl: true
  # verify_ssl: true
  # max_retries: 3
  # default_measurement: state
  # tags:
  #  instance: prod
  #  source: hass

## Open Z-Wave configuration!
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_networkkey
  # config_path: /srv/hass/src/python-openzwave/openzwave/config

## Vera gateway for Z-Wave & Zigbee
vera:
  vera_controller_url: !secret vera_url

## Xiaomi component for temp sensors and buttons
xiaomi_aqara:
  gateways:
   - mac: !secret mac_address_xiaomi
     key: !secret xiaomi_password

## Enable Google Assistant API
google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  # agent_user_id: google_assistant_agent_user_id
  api_key: google_assistant_api_key
  exposed_domains:
     - switch
     - light
    #  - cover
     - media_player
     - group
    #  - fan
     - scene
     - script
     - climate
    #  - input_number
    #  - input_boolean
    #  - input_select
  entity_config:
    group.bedroom_things:
      name: Bedroom Things
      aliases:
        - Bedroom Stuff
    group.livingroom_things:
      name: Livingroom Things
      aliases:
        - Livingroom Stuff
        - Living room Stuff
    # switch.pi_door_strike:
    #   name: Door Strike
    #   aliases:
    #     - Buzz the door
    # group.optimus:
    #   name: optimus
    #   aliases:
    #     - workstation
    #     - the key to vector sigma
    # group.soundwave:
    #   name: soundwave
    #   aliases:
    #     - server
    #     - the tape deck

## Ring.com doorbell
ring:
  username: !secret ring_username
  password: !secret ring_password

sabnzbd:
  api_key: !secret apikey_sabnzbd
  host: 192.168.178.103
  name: sab
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

## Pushbullet Token/API setup (Disabled in January)
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret apikey_pushbullet

mqtt:
#  broker: 127.0.0.1
  broker: 192.168.178.130
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
#  certificate: /home/paulus/dev/addtrustexternalcaroot.crt
#  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

media_player:
  - platform: cast
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: true
    use_custom_entity_ids: false
    use_episode_art: false

climate:
  - platform: generic_thermostat
    name: House Heating
    heater: switch.pi_boiler_switch
    ## Multi-sensor 6
    # target_sensor: !secret 6in1_sensor_temp_2
    ## Xiaomi temp sensor
    target_sensor: sensor.temperature_158d00019ce72e
    min_temp: 10
    max_temp: 25
    target_temp: 21
    cold_tolerance: 0.3
    hot_tolerance: 0
    icon: mdi:guage
    min_cycle_duration:
      minutes: 1
      # seconds: 5

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

light:
  - platform: yeelight
    devices:
      192.168.178.151:
        name: Yeelight 1
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.152:
        name: Yeelight 2
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.153:
        name: Yeelight 3
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)
      192.168.178.154:
        name: Yeelight 4
        transition: 500
        # use_music_mode: True #(defaults to False)
        # save_on_change: False #(defaults to True)

## Weather Prediction
sensor:
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: disk_use
        arg: /
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
  # Tracking my current location to home, driving
  - platform: google_travel_time
    name: Travel Time To Home Drive
    api_key: !secret google_maps_apikey
    origin: device_tracker.kareem_ot
    destination: zone.home
  # Tracking home location to work, driving
  - platform: google_travel_time
    name: Travel Home To Work Drive
    api_key: !secret google_maps_apikey
    origin: zone.home
    destination: zone.work
    # destination: place_id: ChIJa81X5ekJxkcRlQMFMl77x-c
  # Tracking work location to home, driving
  - platform: google_travel_time
    name: Travel Work To Home Drive
    api_key: !secret google_maps_apikey
    origin: zone.work
    # origin: place_id: ChIJa81X5ekJxkcRlQMFMl77x-c
    destination: zone.home
  # Tracking my current location to home, public transport
  - platform: google_travel_time
    name: Travel Time To Home Public
    api_key: !secret google_maps_apikey
    origin: device_tracker.kareem_ot
    destination: zone.home
    options:
      mode: transit
  # Tracking home location to work, public transport
  - platform: google_travel_time
    name: Travel Home To Work Public
    api_key: !secret google_maps_apikey
    origin: zone.home
    destination: zone.work
    options:
      mode: transit
  # Tracking work location to home, public transport
  - platform: google_travel_time
    name: Travel Work To Home Public
    api_key: !secret google_maps_apikey
    origin: zone.work
    destination: zone.home
    options:
      mode: transit
  - platform: time_date
    display_options:
      - 'date'
      - 'date_time'
      - 'time'
      # - 'time_date'
      # - 'time_utc'
      - 'beat'
  - platform: wunderground
    api_key: !secret apikey_wunderground
    monitored_conditions:
      - alerts
      - dewpoint_c
      - dewpoint_f
      - dewpoint_string
      - elevation
      - feelslike_c
      - feelslike_f
      - feelslike_string
      - heat_index_c
      - heat_index_f
      - heat_index_string
      - location
      - observation_time
      - precip_1hr_in
      - precip_1hr_metric
      - precip_1hr_string
      - precip_today_in
      - precip_today_metric
      - precip_today_string
      - pressure_in
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - solarradiation
      - station_id
      - temp_c
      - temp_f
      - temperature_string
      - UV
      - visibility_km
      - visibility_mi
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_gust_mph
      - wind_kph
      - wind_mph
      - wind_string
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

switch:
  ## hardware RPi GPIO switches
  - platform: rpi_gpio
    name: RPi GPIO
    invert_logic: true
    ports:
      2: Pi Boiler Switch # heating
      3: Pi Door Strike   # door strike
      4: Pi Switch 3 (4)     # 
      17: Pi Switch 4 (17)   # 
#      18: Pi Light Hall Upstairs    # light hallway upstairs
#      27: Pi Light Hall Downstairs  # light hallway downstairs
#      22: Pi Light Livigroom Center # light livingroom center
#      23: Pi Light Coatroom         # light coat room
##24 rf tx
##12 rf rx

  ## Hardware RF via GPIO
  - platform: rpi_rf
    gpio: 24
    switches:
      rf_light_test1:
        code_on: !secret rf1_code_on
        code_off: !secret rf1_code_off
      rf_light_test2:
        pulselength: 200
        code_on: !secret rf2_code_on
        code_off: !secret rf2_code_off
      rf_light_test3:
        protocol: 5
        code_on: !secret rf3_code_on
        code_off: !secret rf3_code_off
        #signal_repetitions: 15

  ## activate/deactivate optimus10
  - platform: wake_on_lan
    name: Computer OPTIMUS
    mac_address: !secret mac_address_optimus
    icon: mdi:lan-connect
    #host: 192.168.178.120
    turn_off:
      service: shell_command.sleep_optimus

  - platform: wake_on_lan
    name: Computer SOUNDWAVE
    mac_address: !secret mac_address_soundwave
    icon: mdi:lan-connect
    #host: 192.168.178.100
    #turn_off:
      #service: shell_command.sleep_soundwave

  ## replaced with shell_command
  #- platform: command_line
    #switches:
      #PC:
        #offcmd: 'net rpc shutdown -I 192.168.X.X -U user%password'
        #offcmd: '/usr/bin/curl -X GET "http://192.168.178.120:7760/suspend"'

shell_command:
  sleep_optimus: '/usr/bin/curl -X GET "http://192.168.178.120:7760/suspend"'
  ## More info: http://www.ireksoftware.com/SleepOnLan
  sleep_soundwave: '/usr/bin/curl -X GET "http://192.168.178.100:7760/suspend"'
  ## More info: http://www.ireksoftware.com/SleepOnLan

# Front Page Input States and Options, used for Automation
input_select:
  house_presence:
    name: Who's Home?
    options:
      - Home
      - Nobody Home
      - Lady and The Tramp
      - lady ALONE
      - Night
      # - Warm House
      # - Visitors
      # - Visitors with Kids
      # - Open Door!
      # - Intruder!
      # - Emergency!
    initial: Nobody Home
    icon: mdi:home-map-marker

input_boolean:
  vacation_mode:
    name: "On Vacation"
    initial: off
    icon: mdi:airplane

  friend_visiting:
    name: "Friend Visiting"
    initial: off
    icon: mdi:human-greeting

  kids_in_the_house:
    name: "Kids in the House"
    initial: off
    icon: mdi:human-child

input_number:
  target_temp:
    name: Target Temp
    initial: 20
    min: 14
    max: 25
    step: 1
    mode: slider
    unit_of_measurement: °C  
    icon: mdi:thermometer-lines
  rest_temp:
    name: Rest Temp
    initial: 17
    min: 14
    max: 25
    step: 1
    mode: slider
    unit_of_measurement: °C  
    icon: mdi:thermometer-lines
  away_temp:
    name: Away Temp
    initial: 14
    min: 14
    max: 25
    step: 1
    mode: slider
    unit_of_measurement: °C  
    icon: mdi:thermometer-lines