## switches for using RF_Bridge via MQTT
- platform: mqtt
  name: "RFRelay15"
  command_topic: cmnd/RF_Bridge/rfcode
  availability_topic: "tele/RF_Bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "#555533"
  payload_off: "#555433"
  optimistic: true

- platform: mqtt
  name: "RFRelay15_Program"
  command_topic: cmnd/RF_Bridge/rfcode
  availability_topic: "tele/RF_Bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "#555433"
  payload_off: "#555533"
  optimistic: true

- platform: mqtt
  name: "RFRelay1"
  command_topic: cmnd/RF_Bridge/rfcode
  availability_topic: "tele/RF_Bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "#555503"
  payload_off: "#555403"
  optimistic: true

- platform: mqtt
  name: "RFRelay1_Program"
  command_topic: cmnd/RF_Bridge/rfcode
  availability_topic: "tele/RF_Bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "#555403"
  payload_off: "#555503"
  optimistic: true
