# MQTT switches for Relay4Cs etc

- platform: mqtt
  name: "Relay4C1_1"
  state_topic: "stat/Relay4C1/POWER1"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/Relay4C1/POWER1"
  availability_topic: "tele/Relay4C1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Relay4C1_2"
  state_topic: "stat/Relay4C1/POWER2"
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "cmnd/Relay4C1/POWER2"
  availability_topic: "tele/Relay4C1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Relay4C1_3"
  state_topic: "stat/Relay4C1/POWER3"
  value_template: "{{ value_json.POWER3 }}"
  command_topic: "cmnd/Relay4C1/POWER3"
  availability_topic: "tele/Relay4C1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Relay4C1_4"
  state_topic: "stat/Relay4C1/POWER4"
  value_template: "{{ value_json.POWER4 }}"
  command_topic: "cmnd/Relay4C1/POWER4"
  availability_topic: "tele/Relay4C1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
