# MQTT switches for Sonoffs etc
#– platform: mqtt
#  name: “sonoff1795”
#  state_topic: “stat/sonoff-1795/RESULT”
#  value_template: ‘{{ value_json[“POWER1”] }}’
#  command_topic: “cmnd/sonoff-1795/POWER1”
#  availability_topic: “tele/sonoff-1795/LWT”
#  qos: 1
#  payload_on: “ON”
#  payload_off: “OFF”
#  payload_available: “Online”
#  payload_not_available: “Offline”
#  retain: true 

- platform: mqtt
  name: "sonoff1"
  state_topic: "stat/sonoff1/POWER1"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/sonoff1/POWER1"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "sonoff2"
  state_topic: "stat/sonoff2/POWER1"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/sonoff2/POWER1"
  availability_topic: "tele/sonoff2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "sonoff3"
  state_topic: "stat/sonoff3/POWER1"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/sonoff3/POWER1"
  availability_topic: "tele/sonoff3/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "sonoff4"
  state_topic: "stat/sonoff4/POWER1"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/sonoff4/POWER1"
  availability_topic: "tele/sonoff4/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
