## Hardware RF via GPIO
- platform: rpi_rf
  gpio: 24
  switches:
    rf_light_test1:
      code_on: !secret rf1_code_on
      code_off: !secret rf1_code_off
    rf_light_test2:
      pulselength: 200
      code_on: !secret rf2_code_on
      code_off: !secret rf2_code_off
    rf_light_test3:
      protocol: 5
      code_on: !secret rf3_code_on
      code_off: !secret rf3_code_off
      # signal_repetitions: 15
