## hardware RPi GPIO switches
- platform: rpi_gpio
  name: RPi GPIO
  invert_logic: true
  ports:
    2: Pi Boiler Switch # heating
    3: Pi Door Strike   # door strike
    4: Pi Switch 3 (4)     # 
    17: Pi Switch 4 (17)   # 
    # 18: Pi Light Hall Upstairs    # light hallway upstairs
    # 27: Pi Light Hall Downstairs  # light hallway downstairs
    # 22: Pi Light Livigroom Center # light livingroom center
    # 23: Pi Light Coatroom         # light coat room
    # 24 rf tx
    # 12 rf rx

## Hardware RF via GPIO
- platform: rpi_rf
  gpio: 24
  switches:
    rf_light_test1:
      code_on: !secret rf1_code_on
      code_off: !secret rf1_code_off
    rf_light_test2:
      pulselength: 200
      code_on: !secret rf2_code_on
      code_off: !secret rf2_code_off
    rf_light_test3:
      protocol: 5
      code_on: !secret rf3_code_on
      code_off: !secret rf3_code_off
      # signal_repetitions: 15

## activate/deactivate optimus10
- platform: wake_on_lan
  name: Computer OPTIMUS
  mac_address: !secret mac_address_optimus
  icon: mdi:lan-connect
  # host: 192.168.178.120
  turn_off:
    service: shell_command.sleep_optimus

- platform: wake_on_lan
  name: Computer SOUNDWAVE
  mac_address: !secret mac_address_soundwave
  icon: mdi:lan-connect
  # host: 192.168.178.100
  # turn_off:
  #   service: shell_command.sleep_soundwave

## replaced with shell_command
# - platform: command_line
#   switches:
#     PC:
#       offcmd: 'net rpc shutdown -I 192.168.X.X -U user%password'
#       offcmd: '/usr/bin/curl -X GET "http://192.168.178.120:7760/suspend"'