## Ring Sensor 
## https://www.home-assistant.io/components/ring/#sensor
- platform: ring
#   monitored_conditions:
#     - battery
#     - last_activity
#     - last_ding
#     - last_motion
#     - volume
#     - wifi_signal_category
#     - wifi_signal_strength
