## Templates of sensors
## Good writup here for making graphs: https://www.hiscorebob.lu/2017/11/home-assistant-plot-a-graph-with-objects-attributes/

- platform: template
  sensors:
    # ## Battery sensors
    # ## https://github.com/arsaboo/homeassistant-config/blob/master/sensor.yaml#L184
    # battery_status:
    #   friendly_name: "Battery Status"
    #   value_template: >-
    #     {%- set threshold = 25 -%}
    #     {%- set domains = ['light', 'switch', 'sensor', 'zwave', 'binary_sensor', 'camera', 'fan'] -%}
    #     {%- for domain in domains -%}
    #     {%- for item in states[domain] if ((item.attributes.battery_low is defined and item.attributes['battery_low'] == true) or (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold)) -%}
    #         {{ item.name }}{%- if not loop.last %}, {% endif -%}
    #     {%- endfor -%}
    #     {%- endfor -%}

    ## Sensors for Xiaomi Air Purifier 2S
    attribute_fan_aqi:
      friendly_name: "Air Quality Rating"
      value_template: "{{ states.fan.air_purifier_2s.attributes.aqi }}"
      unit_of_measurement:  level
    attribute_fan_favorite_level:
      friendly_name: "Air Air Purifier 2S Fave Level"
      value_template: "{{ states.fan.air_purifier_2s.attributes.favorite_level }}"
      unit_of_measurement:  level
    attribute_fan_temperature:
      friendly_name: "Air Purifier 2S Temperature"
      value_template: "{{ states.fan.air_purifier_2s.attributes.temperature }}"
      unit_of_measurement:  level
    attribute_fan_filter_hours_used:
      friendly_name: "Air Purifier 2S Filter Hours Used"
      value_template: "{{ states.fan.air_purifier_2s.attributes.filter_hours_used }}"
      unit_of_measurement:  hrs
    attribute_fan_filter_life_remaining:
      friendly_name: "Air Purifier 2S Filter Life Remaining"
      value_template: "{{ states.fan.air_purifier_2s.attributes.filter_life_remaining }}"
      unit_of_measurement:  life
