- platform: darksky
  api_key: !secret apikey_darksky
  # name:
  # forecast:
  language: en
  # latitude
  # longitude
  monitored_conditions:
    - summary # A human-readable text summary.
    - icon # A machine-readable text summary, suitable for selecting an icon for display. See Dark Sky API documentation for the list of possible values.
    - precip_type # The type of precipitation occurring at the given time. If precip_intensity is zero, then this property will be unknown. See Dark Sky API documentation for the list of possible values.
    - precip_intensity # The intensity of precipitation occurring at the given time. This value is conditional on probability (that is, assuming any precipitation occurs at all).
    - precip_probability # The probability of precipitation occurring, in percents.
    - precip_accumulation # The amount of snowfall accumulation expected to occur. If no snowfall is expected, this property will be undefined.
    - temperature # The air temperature.
    - apparent_temperature # The apparent (or “feels like”) temperature.
    - dew_point # The dew point.
    - wind_speed # The wind speed.
    - wind_gust # The wind gust speed.
    - wind_bearing # The direction that the wind is coming from in degrees, with true north at 0° and progressing clockwise. If wind_speed is 0, then this value is unknown.
    - cloud_cover # The percentage of sky occluded by clouds.
    - humidity # The relative humidity.
    - pressure # The sea-level air pressure in millibars.
    - visibility # The average visibility.
    - ozone # The columnar density of total atmospheric ozone at the given time in Dobson units.
    - minutely_summary # A human-readable text summary for the next hour.
    - hourly_summary # A human-readable text summary for the next two days.
    - daily_summary # A human-readable text summary for the next week.
    - temperature_high # The daytime high temperature.
    - temperature_low # The overnight low temperature.
    - apparent_temperature_high # The daytime high apparent temperature.
    - apparent_temperature_low # The overnight low apparent temperature.
    - precip_intensity_max # The maximum value of precip_intensity during a given day.
    - uv_index # The UV index.
    - moon_phase # The fractional part of the lunation number during the given day: a value of 0 corresponds to a new moon, 0.25 to a first quarter moon, 0.5 to a full moon, and 0.75 to a last quarter moon.
    - sunrise_time # The time of when the sun will rise during a given day.
    - sunset_time # The time of when the sun will set during a given day.
    - nearest_storm_distance # The approximate distance to the nearest storm in miles.
    - nearest_storm_bearing
