#############################
#### GENERAL AUTOMATIONS ####
#############################

# General Automations, mostly moved to automations.yaml

## Purge Recorder DB history daily
- id: ha_purge_recorder
  alias: HA Purge Recorder
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    service: recorder.purge
    data:
      keep_days: 3
