##########################
### MANUAL AUTOMATIONS ###
##########################

## Turn on bedroom things with button
- id: sw1_bedroom_things
  alias: sw1 Bedroom Things
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186dbec
        click_type: single
  action:
    - service: homeassistant.toggle
      entity_id:
      - switch.neocoolcamplug12a_2_21 # lamp
      - switch.neocoolcamplug12a_3_22 # tv

## Toggle nightlight with button double-click
- id: sw1_gateway_nightlight
  alias: sw1 Gateway Nightlight
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186dbec
        click_type: double
  action:
    - service: homeassistant.toggle
      entity_id: light.gateway_light_34ce008bee96

## Turn off all lights on long press
- id: sw1_lights_out
  alias: sw1 Lights Out
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186dbec
        click_type: long_click_press
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.lights_automate_bedrooms
    - service: homeassistant.turn_on
      entity_id:
      - script.lights_cancel_all_timers
    - service: homeassistant.turn_on
      entity_id:
      - script.lights_off_at_home
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008bee96
        brightness: 40
        transition: 2
        color_name: red

## House Lockdown
- id: sw2_lockdown_house
  alias: sw2 Lockdown House
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00018726b8
        click_type: single
  action:
  - service: homeassistant.turn_on
    entity_id:
      - script.home_lockdown_everything_off

## House Disarm
- id: sw2_disarm_house
  alias: sw2 Disarm House
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00018726b8
        click_type: double
  action:
  - service: homeassistant.turn_on
    entity_id:
      - script.home_lockdown_disarm

## Open door strike long press
- id: sw2_door_strike
  alias: sw2 Door Strike
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00018726b8
        click_type: long_click_press
  action:
    - service: homeassistant.toggle
      entity_id:
        - switch.relay4c1_2
    - service: notify.pushbullet
      data:
        target: !secret email_target_pushbullet
        title: 'Home Assistant - Door strike activated!'
        message: "Door Strike activated!"

## Activate OPTIMUS single click
- id: sw3_activate_optimus
  alias: sw3 Activate OPTIMUS
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001870a09
        click_type: single
  action:
    # ## Turn on desk lamp
    # - service: switch.turn_on
    #   entity_id: !secret sonoff_4
      ## Turn on Triple Monitors
    - service: homeassistant.turn_on
      entity_id: !secret plug_1
      ## wait x seconds
    - delay: 00:00:05
      ## Turn on OPTIMUS
    - service: homeassistant.turn_on
      entity_id: switch.optimus

## Turn off OPTIMUS double click
- id: sw3_deactivate_optimus
  alias: sw3 Deactivate OPTIMUS
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001870a09
        click_type: double
  action:
      ## Turn off OPTIMUS
    - service: homeassistant.turn_off
      entity_id: switch.optimus
      ## wait x seconds
    - delay: 00:00:05
      ## Turn off Triple Monitors
    - service: homeassistant.turn_off
      entity_id: !secret plug_1
    # ## Turn off desk lamp
    # - service: switch.turn_off
    #   entity_id: !secret sonoff_4

## Toggle Gameroom Light with button long press
- id: sw3_gameroom_light
  alias: sw1 Gameroom Light
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001870a09
        click_type: long_click_press
  action:
    - service: homeassistant.toggle
      entity_id: light.yeelight_4

## Turn on Livingroom things with button
- id: sw4_livingroom_things
  alias: sw4 Livingroom Things
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001870ad7
        click_type: single
  action:
    - service: homeassistant.toggle
      entity_id:
      - switch.neocoolcamplug12a_6_25 # livingroom tv

## Toggle Livingroom Spots with button long press
- id: sw4_livingroom_spots
  alias: sw4 Livingroom Spots
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001870ad7
        click_type: long_click_press
  action:
    - service: homeassistant.toggle
      entity_id: light.fibaro_dimmer_2_1_8

## Activate monitors+lamp on single click
- id: sw5_workiva_time
  alias: sw5 Workiva Time
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186e64a
        click_type: single
  action:
    # ## Turn on desk lamp
    # - service: switch.turn_on
    #   entity_id: !secret sonoff_4
      ## Turn on Triple Monitors
    - service: switch.turn_on
      entity_id: !secret plug_1

## Deactivate monitors+lamp off long press click
- id: sw5_workiva_done
  alias: sw5 Workiva Done
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186e64a
        click_type: double
  action:
      ## Turn off Triple Monitors
    - service: switch.turn_off
      entity_id: !secret plug_1
    #   ## wait x seconds
    # - delay: 00:00:10
    # ## Turn off desk lamp
    # - service: switch.turn_off
    #   entity_id: !secret sonoff_4

## Fibaro button from Vera scene
- alias: button_1_pressed
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id:
          - scene.vera_button_1
          - scene.vera_button_2
          - scene.vera_button_3
          - scene.vera_button_4
          - scene.vera_button_5
      domain: scene
      service: turn_on
  action:
    - service: notify.pushbullet
      data:
        target: !secret email_target_pushbullet
        title: 'Home Assistant - Button Pressed!'
        message: "Button 1 pressed!"
