## Start timer when movement detected upstairs
- alias: movement upstairs start timer
  id: movement_upstairs_start_timer
  trigger:
  - platform: state
    entity_id: !secret 6in1_sensor_move_1
    to: "on"
  condition:
    condition: and
    conditions:
    - condition: time
      after: "06:00:00"
      before: "01:00:00"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.presence_house
        state: Home
      - condition: state
        entity_id: input_select.presence_house
        state: Home Guests
      - condition: state
        entity_id: input_select.presence_house
        state: Away Guests
  action:
  - service: timer.cancel
    entity_id: timer.light_upstairs
  - service: timer.start
    entity_id: timer.light_upstairs

# When timer is started, turn on light
- alias: Timer started light_upstairs
  id: 'timer_started_light_upstairs'
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.light_upstairs
  action:
  - service: light.turn_on
    data:
      entity_id: !secret light_upstairs
      transition: 2
      brightness: 255
      kelvin: 3000
  # - service: notify.pushbullet
  #   data: 
  #     target: !secret email_target_pushbullet
  #     message: "debug upstairs light on"

# When timer is finished, turn off light
- alias: Timer finished light_upstairs
  id: 'timer_finished_light_upstairs'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.light_upstairs
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.keep_lights_on
      state: "off"
  action:
  - service: timer.cancel
    entity_id: timer.light_upstairs
  - service: light.turn_off
    data:
      entity_id: !secret light_upstairs
  # - service: notify.pushbullet
  #   data: 
  #     target: !secret email_target_pushbullet
  #     message: "debug upstairs light off"
