## Start timer when movement detected closet at night
- alias: movement closet at night start timer
  id: movement_closet_at_night_start_timer
  trigger:
  - platform: state
    entity_id: !secret coolcam_motion_sensor_5
    to: "on"
  condition:
    condition: and
    conditions:
    - condition: time
      after: "01:00:00"
      before: "06:00:00"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.presence_house
        state: Home
      - condition: state
        entity_id: input_select.presence_house
        state: Home Guests
      - condition: state
        entity_id: input_select.presence_house
        state: Away Guests
  action:
  - service: timer.cancel
    entity_id: timer.light_closet_night
  - service: timer.start
    entity_id: timer.light_closet_night

# When timer is started, turn on light
- alias: Timer started light_closet_night
  id: 'timer_started_light_closet_night'
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.light_closet_night
  action:
  - service: light.turn_on
    data:
      entity_id: !secret light_closet
      transition: 2
      brightness: 180
      color_name: red

# When timer is finished, turn off light
- alias: Timer finished light_closet_night
  id: 'timer_finished_light_closet_night'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.light_closet_night
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.keep_lights_on
      state: "off"
  action:
  - service: timer.cancel
    entity_id: timer.light_closet_night
  - service: light.turn_off
    data:
      entity_id: !secret light_closet
