## Start timer when movement detected livingroom_table
- alias: movement livingroom_table start timer
  id: movement_livingroom_table_start_timer
  trigger:
  - platform: state
    entity_id: !secret 6in1_sensor_move_2
    to: "on"
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: state
      entity_id: !secret plug_6
      state: "off"
    - condition: state
      entity_id: !secret light_table_1
      state: "off"
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.presence_house
        state: Home
      - condition: state
        entity_id: input_select.presence_house
        state: Home Guests
      - condition: state
        entity_id: input_select.presence_house
        state: Away Guests
  action:
  - service: timer.cancel
    entity_id: timer.light_livingroom_table
  - service: timer.start
    entity_id: timer.light_livingroom_table

# When timer is started, turn on light
- alias: Timer started light_livingroom_table
  id: 'timer_started_light_livingroom_table'
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.light_livingroom_table
  action:
  - service: light.turn_on
    data:
      entity_id: !secret light_table_1
      transition: 2
      brightness: 120

# When timer is finished, turn off light
- alias: Timer finished light_livingroom_table
  id: 'timer_finished_light_livingroom_table'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.light_livingroom_table
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.keep_lights_on
      state: "off"
  action:
  - service: timer.cancel
    entity_id: timer.light_livingroom_table
  - service: light.turn_off
    data:
      entity_id: !secret light_table_1
