## Start timer when movement detected entrance
- alias: movement entrance start timer
  id: movement_entrance_start_timer
  trigger:
  - platform: state
    entity_id: !secret coolcam_motion_sensor_1
    to: "on"
  condition:
    condition: and
    conditions:
    # - condition: time
    #   after: "06:00:00"
    #   before: "01:00:00"
    # - condition: state
    #   entity_id: sun.sun
    #   state: "below_horizon"
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.presence_house
        state: Home
      - condition: state
        entity_id: input_select.presence_house
        state: Home Guests
      - condition: state
        entity_id: input_select.presence_house
        state: Away Guests
  action:
  - service: timer.cancel
    entity_id: timer.light_entrance
  - service: timer.start
    entity_id: timer.light_entrance

# When timer is started, turn on light
- alias: Timer started light_entrance
  id: 'timer_started_light_entrance'
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.light_entrance
  action:
  - service: light.turn_on
    data:
      entity_id: !secret light_entrance
      transition: 2
      brightness: 255
      kelvin: 3000

# When timer is finished, turn off light
- alias: Timer finished light_entrance
  id: 'timer_finished_light_entrance'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.light_entrance
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.keep_lights_on
      state: "off"
  action:
  - service: timer.cancel
    entity_id: timer.light_entrance
  - service: light.turn_off
    data:
      entity_id: !secret light_entrance
