## Play Ring on Gameroom Chromecast
- alias: Ring Play on Gameroom Chromecast
  trigger:
    platform: state
    entity_id:  binary_sensor.ring_front_door_ding
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.kareem
      state: "home"
    - condition: state
      entity_id: input_select.presence_house
      state: Home
    # - condition: or
    #   conditions:
    #   - condition: state
    #     entity_id: device_tracker.wfnd_00152
    #     state: "home"
    #   - condition: state
    #     entity_id: device_tracker.wfnd_00152_docklan
    #     state: "home"
    #   - condition: state
    #     entity_id: device_tracker.optimus
    #     state: "home"
    # - condition: template
    #   value_template: "{{ (states.binary_sensor.ccammotionsensor_4_69.attributes['No motion since']) | int  > 60  }}"
  action:
    service: camera.play_stream
    data:
      entity_id: camera.front_door
      media_player: media_player.chromecast_tv_1

- alias: 'Ring Save the video when the doorbell is pushed'
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_ding
    to: 'on'
  action:
  - service: downloader.download_file
    data:
      url: "{{ state_attr('camera.front_door', 'video_url') }}"
      subdir: "{{state_attr('camera.front_door', 'friendly_name')}}"
      filename: "{{state_attr('camera.front_door', 'friendly_name')}}"