## Enable Chromecast
# - platform: cast
## Enable Plex Media Server Integration
- platform: plex
  show_all_controls: false
  use_episode_art: true
  remove_unavailable_clients: false
  client_remove_interval: 600
  entity_namespace: 'plex'
  scan_interval: 5
