## Managing tracked devices
## https://www.home-assistant.io/components/device_tracker/

## NMAP tracking for devices in home
## https://www.home-assistant.io/components/nmap_tracker/
- platform: nmap_tracker
  track_new_devices: yes
  hosts: 192.168.178.1/24
  interval_seconds: 30
  consider_home: 600 ## was 900
  home_interval: 10
  scan_options: " --privileged -sP "
# sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap
